export const browserLanguages = {
  "Afrikaans (South Africa)": "af-ZA",
  "Amharic (Ethiopia)": "am-ET",
  "Arabic (Algeria)": "ar-DZ",
  "Arabic (Bahrain)": "ar-BH",
  "Arabic (Egypt)": "ar-EG",
  "Arabic (Iraq)": "ar-IQ",
  "Arabic (Israel)": "ar-IL",
  "Arabic (Jordan)": "ar-JO",
  "Arabic (Kuwait)": "ar-KW",
  "Arabic (Lebanon)": "ar-LB",
  "Arabic (Morocco)": "ar-MA",
  "Arabic (Oman)": "ar-OM",
  "Arabic (Qatar)": "ar-QA",
  "Arabic (Saudi Arabia)": "ar-SA",
  "Arabic (State of Palestine)": "ar-PS",
  "Arabic (Syria)": "ar-SY",
  "Arabic (Tunisia)": "ar-TN",
  "Arabic (UAE)": "ar-AE",
  "Arabic (Yemen)": "ar-YE",
  "Basque (Spain)": "eu-ES",
  "Bulgarian (Bulgaria)": "bg-BG",
  "Catalan (Spain)": "ca-ES",
  "Chinese, Mandarin (Simplified, China)": "zh-CN",
  "Chinese, Cantonese (Traditional, Hong Kong)": "zh-HK",
  "Chinese, Mandarin (Traditional, Taiwan)": "zh-TW",
  "Croatian (Croatia)": "hr-HR",
  "Czech (Czech Republic)": "cs-CZ",
  "Danish (Denmark)": "da-DK",
  "Dutch (Belgium)": "nl-BE",
  "Dutch (Netherlands)": "nl-NL",
  "English (Australia)": "en-AU",
  "English (Canada)": "en-CA",
  "English (Ghana)": "en-GH",
  "English (India)": "en-IN",
  "English (Ireland)": "en-IE",
  "English (Kenya)": "en-KE",
  "English (New Zealand)": "en-NZ",
  "English (Nigeria)": "en-NG",
  "English (Philippines)": "en-PH",
  "English (South Africa)": "en-ZA",
  "English (Tanzania)": "en-TZ",
  "English (United Kingdom)": "en-GB",
  "English (United States)": "en-US",
  "Estonian (Estonia)": "et-EE",
  "Filipino (Philippines)": "fil-PH",
  "Finnish (Finland)": "fi-FI",
  "French (Canada)": "fr-CA",
  "French (France)": "fr-FR",
  "Galician (Spain)": "gl-ES",
  "German (Germany)": "de-DE",
  "Greek (Greece)": "el-GR",
  "Gujarati (India)": "gu-IN",
  "Hebrew (Israel)": "he-IL",
  "Hindi (India)": "hi-IN",
  "Hungarian (Hungary)": "hu-HU",
  "Icelandic (Iceland)": "is-IS",
  "Indonesian (Indonesia)": "id-ID",
  "Italian (Italy)": "it-IT",
  "Japanese (Japan)": "ja-JP",
  "Javanese (Indonesia)": "jv-ID",
  "Kannada (India)": "kn-IN",
  "Kazakh (Kazakhstan)": "kk-KZ",
  "Khmer (Cambodia)": "km-KH",
  "Korean (South Korea)": "ko-KR",
  "Lao (Laos)": "lo-LA",
  "Latvian (Latvia)": "lv-LV",
  "Lithuanian (Lithuania)": "lt-LT",
  "Macedonian (North Macedonia)": "mk-MK",
  "Malay (Malaysia)": "ms-MY",
  "Malayalam (India)": "ml-IN",
  "Marathi (India)": "mr-IN",
  "Mongolian (Mongolia)": "mn-MN",
  "Nepali (Nepal)": "ne-NP",
  "Norwegian Bokmål (Norway)": "nb-NO",
  "Persian (Iran)": "fa-IR",
  "Polish (Poland)": "pl-PL",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  "Punjabi (India)": "pa-IN",
  "Romanian (Romania)": "ro-RO",
  "Russian (Russia)": "ru-RU",
  "Serbian (Serbia)": "sr-RS",
  "Sinhala (Sri Lanka)": "si-LK",
  "Slovak (Slovakia)": "sk-SK",
  "Slovenian (Slovenia)": "sl-SI",
  "Spanish (Argentina)": "es-AR",
  "Spanish (Bolivia)": "es-BO",
  "Spanish (Chile)": "es-CL",
  "Spanish (Colombia)": "es-CO",
  "Spanish (Costa Rica)": "es-CR",
  "Spanish (Dominican Republic)": "es-DO",
  "Spanish (Ecuador)": "es-EC",
  "Spanish (El Salvador)": "es-SV",
  "Spanish (Guatemala)": "es-GT",
  "Spanish (Honduras)": "es-HN",
  "Spanish (Mexico)": "es-MX",
  "Spanish (Nicaragua)": "es-NI",
  "Spanish (Panama)": "es-PA",
  "Spanish (Paraguay)": "es-PY",
  "Spanish (Peru)": "es-PE",
  "Spanish (Puerto Rico)": "es-PR",
  "Spanish (Spain)": "es-ES",
  "Spanish (United States)": "es-US",
  "Spanish (Uruguay)": "es-UY",
  "Spanish (Venezuela)": "es-VE",
  "Sundanese (Indonesia)": "su-ID",
  "Swahili (Kenya)": "sw-KE",
  "Swahili (Tanzania)": "sw-TZ",
  "Swedish (Sweden)": "sv-SE",
  "Tamil (India)": "ta-IN",
  "Tamil (Malaysia)": "ta-MY",
  "Tamil (Singapore)": "ta-SG",
  "Tamil (Sri Lanka)": "ta-LK",
  "Telugu (India)": "te-IN",
  "Thai (Thailand)": "th-TH",
  "Turkish (Turkey)": "tr-TR",
  "Ukrainian (Ukraine)": "uk-UA",
  "Urdu (India)": "ur-IN",
  "Urdu (Pakistan)": "ur-PK",
  "Uzbek (Uzbekistan)": "uz-UZ",
  "Vietnamese (Vietnam)": "vi-VN",
  "Zulu (South Africa)": "zu-ZA"
};

export const LANGUAGES = {
  "Abkhaz": "ab",
  "Acehnese": "ace",
  "Acholi": "ach",
  "Afrikaans": "af",
  "Albanian": "sq",
  "Alur": "alz",
  "Amharic": "am",
  "Arabic": "ar",
  "Armenian": "hy",
  "Assamese": "as",
  "Awadhi": "awa",
  "Aymara": "ay",
  "Azerbaijani": "az",
  "Balinese": "ban",
  "Bambara": "bm",
  "Bashkir": "ba",
  "Basque": "eu",
  "Batak Karo": "btx",
  "Batak Simalungun": "bts",
  "Batak Toba": "bbc",
  "Belarusian": "be",
  "Bemba": "bem",
  "Bengali": "bn",
  "Betawi": "bew",
  "Bhojpuri": "bho",
  "Bikol": "bik",
  "Bosnian": "bs",
  "Breton": "br",
  "Bulgarian": "bg",
  "Buryat": "bua",
  "Cantonese": "yue",
  "Catalan": "ca",
  "Cebuano": "ceb",
  "Chichewa (Nyanja)": "ny",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Traditional)": "zh-TW",
  "Chuvash": "cv",
  "Corsican": "co",
  "Crimean Tatar": "crh",
  "Croatian": "hr",
  "Czech": "cs",
  "Danish": "da",
  "Dinka": "din",
  "Divehi": "dv",
  "Dogri": "doi",
  "Dombe": "dov",
  "Dutch": "nl",
  "Dzongkha": "dz",
  "English": "en",
  "Esperanto": "eo",
  "Estonian": "et",
  "Ewe": "ee",
  "Fijian": "fj",
  "Filipino (Tagalog)": "fil",
  "Finnish": "fi",
  "French": "fr",
  "French (French)": "fr-FR",
  "French (Canadian)": "fr-CA",
  "Frisian": "fy",
  "Fulfulde": "ff",
  "Ga": "gaa",
  "Galician": "gl",
  "Ganda (Luganda)": "lg",
  "Georgian": "ka",
  "German": "de",
  "Greek": "el",
  "Guarani": "gn",
  "Gujarati": "gu",
  "Haitian Creole": "ht",
  "Hakha Chin": "cnh",
  "Hausa": "ha",
  "Hawaiian": "haw",
  "Hebrew": "iw",
  "Hiligaynon": "hil",
  "Hindi": "hi",
  "Hmong": "hmn",
  "Hungarian": "hu",
  "Hunsrik": "hrx",
  "Icelandic": "is",
  "Igbo": "ig",
  "Iloko": "ilo",
  "Indonesian": "id",
  "Irish": "ga",
  "Italian": "it",
  "Japanese": "ja",
  "Javanese": "jw",
  "Kannada": "kn",
  "Kapampangan": "pam",
  "Kazakh": "kk",
  "Khmer": "km",
  "Kiga": "cgg",
  "Kinyarwanda": "rw",
  "Kituba": "ktu",
  "Konkani": "gom",
  "Korean": "ko",
  "Krio": "kri",
  "Kurdish (Kurmanji)": "ku",
  "Kurdish (Sorani)": "ckb",
  "Kyrgyz": "ky",
  "Lao": "lo",
  "Latgalian": "ltg",
  "Latin": "la",
  "Latvian": "lv",
  "Ligurian": "lij",
  "Limburgan": "li",
  "Lingala": "ln",
  "Lithuanian": "lt",
  "Lombard": "lmo",
  "Luo": "luo",
  "Luxembourgish": "lb",
  "Macedonian": "mk",
  "Maithili": "mai",
  "Makassar": "mak",
  "Malagasy": "mg",
  "Malay": "ms",
  "Malay (Jawi)": "ms-Arab",
  "Malayalam": "ml",
  "Maltese": "mt",
  "Maori": "mi",
  "Marathi": "mr",
  "Meadow Mari": "chm",
  "Meiteilon (Manipuri)": "mni-Mtei",
  "Minang": "min",
  "Mizo": "lus",
  "Mongolian": "mn",
  "Myanmar (Burmese)": "my",
  "Ndebele (South)": "nr",
  "Nepalbhasa (Newari)": "new",
  "Nepali": "ne",
  "Northern Sotho (Sepedi)": "nso",
  "Norwegian": "no",
  "Nuer": "nus",
  "Occitan": "oc",
  "Odia (Oriya)": "or",
  "Oromo": "om",
  "Pangasinan": "pag",
  "Papiamento": "pap",
  "Pashto": "ps",
  "Persian": "fa",
  "Polish": "pl",
  "Portuguese": "pt",
  "Portuguese (Portugal)": "pt-PT",
  "Portuguese (Brazil)": "pt-BR",
  "Punjabi": "pa",
  "Punjabi (Shahmukhi)": "pa-Arab",
  "Quechua": "qu",
  "Romani": "rom",
  "Romanian": "ro",
  "Rundi": "rn",
  "Russian": "ru",
  "Samoan": "sm",
  "Sango": "sg",
  "Sanskrit": "sa",
  "Scots Gaelic": "gd",
  "Serbian": "sr",
  "Sesotho": "st",
  "Seychellois Creole": "crs",
  "Shan": "shn",
  "Shona": "sn",
  "Sicilian": "scn",
  "Silesian": "szl",
  "Sindhi": "sd",
  "Sinhala (Sinhalese)": "si",
  "Slovak": "sk",
  "Slovenian": "sl",
  "Somali": "so",
  "Spanish": "es",
  "Sundanese": "su",
  "Swahili": "sw",
  "Swati": "ss",
  "Swedish": "sv",
  "Tajik": "tg",
  "Tamil": "ta",
  "Tatar": "tt",
  "Telugu": "te",
  "Tetum": "tet",
  "Thai": "th",
  "Tigrinya": "ti",
  "Tsonga": "ts",
  "Tswana": "tn",
  "Turkish": "tr",
  "Turkmen": "tk",
  "Twi (Akan)": "ak",
  "Ukrainian": "uk",
  "Urdu": "ur",
  "Uyghur": "ug",
  "Uzbek": "uz",
  "Vietnamese": "vi",
  "Welsh": "cy",
  "Xhosa": "xh",
  "Yiddish": "yi",
  "Yoruba": "yo",
  "Yucatec Maya": "yua",
  "Zulu": "zu"
};